// src/services/mockData.js
// Comprehensive mock dataset & state templates for GramVikas

export const DEFAULT_FARMER_PROFILE = {
  id: 'farmer_001',
  name: 'Raju',
  phone: '9390616956',
  language: 'te', // Default Telugu or English
  location: {
    state: 'Andhra Pradesh',
    district: 'NTR District',
    mandal: 'Vijayawada Rural',
    village: 'Gollapudi',
    latitude: 16.5062,
    longitude: 80.6480,
    addressString: 'Gollapudi, Vijayawada, Andhra Pradesh',
  },
  farm: {
    farmId: 'farm_001',
    name: 'Sri Venkateswara Farm',
    sizeAcres: 3.5,
    soilType: 'Alluvial Soil (ఒండ్రు నేల)',
    irrigationType: 'Drip & Borewell (డ్రిప్ & బోరుబావి)',
    waterAvailability: 'Good (మంచిది)',
    soilReport: {
      nitrogen: 82,
      phosphorus: 42,
      potassium: 48,
      ph: 6.8,
      organicCarbon: 0.58,
      electricalConductivity: 0.42,
      lastTestedDate: '2026-06-15',
    },
  },
  activeCrop: {
    hasCrop: true,
    cropName: 'Paddy (వరి)',
    cropKey: 'Rice',
    variety: 'BPT 5204 (Samba Mahsuri)',
    plantingDate: '2026-07-20',
    cropAgeDays: 30,
    growthStage: 'Vegetative Stage (శాకీయ దశ)',
    totalCycleDays: 135,
    expectedHarvestDate: '2026-12-05',
    healthStatus: 'Healthy (ఆరోగ్యంగా ఉంది)',
    lastIrrigationDate: '2026-08-17',
    nextIrrigationDate: '2026-08-21',
    irrigationStatus: 'due_soon', // 'due_today' | 'due_soon' | 'adequate'
    soilMoisturePercent: 68,
  },
  recentDiseaseScan: null, // or { disease: 'Early Blight', severity: 'moderate', date: '2026-08-18' }
  recentActivities: [
    { id: 'act_1', type: 'irrigation', title: 'Irrigation Completed', titleTe: 'నీటిపారుదల పూర్తయింది', titleHi: 'सिंचाई पूर्ण हुई', date: '2026-08-17' },
    { id: 'act_2', type: 'fertilizer', title: 'Urea (45kg) Applied', titleTe: 'యూరియా (45కిలోలు) వేయబడింది', titleHi: 'यूरिया (45 किग्रा) डाला गया', date: '2026-08-10' },
    { id: 'act_3', type: 'soil_test', title: 'Soil Health Card Updated', titleTe: 'సాయిల్ హెల్త్ కార్డ్ అప్‌డేట్ చేయబడింది', titleHi: 'मृदा स्वास्थ्य कार्ड अपडेट किया गया', date: '2026-06-15' },
  ],
};

export const MOCK_WEATHER_DATA = {
  location: 'Vijayawada, Andhra Pradesh',
  temperature: 31,
  feelsLike: 35,
  condition: 'Partly Cloudy (పాక్షికంగా మేఘావృతం)',
  conditionCode: 'partly_cloudy',
  humidity: 72,
  windSpeedKm: 14,
  rainProbabilityPercent: 20,
  rainfallForecastMm: 0.5,
  uvIndex: 7,
  soilTemperature: 28,
  forecast: [
    { day: 'Today', dayTe: 'ఈరోజు', dayHi: 'आज', tempMax: 33, tempMin: 26, rainChance: 20, icon: 'sun-cloud' },
    { day: 'Tomorrow', dayTe: 'రేపు', dayHi: 'कल', tempMax: 32, tempMin: 25, rainChance: 40, icon: 'cloud-rain' },
    { day: 'Thursday', dayTe: 'గురువారం', dayHi: 'गुरुवार', tempMax: 31, tempMin: 25, rainChance: 60, icon: 'cloud-rain' },
    { day: 'Friday', dayTe: 'శుక్రవారం', dayHi: 'शुक्रवार', tempMax: 32, tempMin: 26, rainChance: 15, icon: 'sun' },
  ],
};

export const MOCK_MANDI_PRICES = [
  {
    crop: 'Paddy (Dhan)',
    cropTe: 'వరి ధాన్యం',
    cropHi: 'धान (चावल)',
    market: 'Vijayawada APMC',
    marketTe: 'విజయవాడ మార్కెట్',
    marketHi: 'विजयवाड़ा मंडी',
    pricePerQuintal: 2320,
    previousPrice: 2280,
    changePercent: +1.75,
    trend: 'up',
    minPrice: 2180,
    maxPrice: 2450,
  },
  {
    crop: 'Tomato',
    cropTe: 'టమాటో',
    cropHi: 'टमाटर',
    market: 'Madanapalle APMC',
    marketTe: 'మదనపల్లె మార్కెట్',
    marketHi: 'मदनपल्ले मंडी',
    pricePerQuintal: 3800,
    previousPrice: 3400,
    changePercent: +11.76,
    trend: 'up',
    minPrice: 3200,
    maxPrice: 4200,
  },
  {
    crop: 'Cotton',
    cropTe: 'పత్తి',
    cropHi: 'कपास',
    market: 'Guntur APMC',
    marketTe: 'గుంటూరు మార్కెట్',
    marketHi: 'गुंटूर मंडी',
    pricePerQuintal: 7450,
    previousPrice: 7500,
    changePercent: -0.67,
    trend: 'down',
    minPrice: 7100,
    maxPrice: 7800,
  },
  {
    crop: 'Chilli (Red)',
    cropTe: 'ఎర్ర మిరప',
    cropHi: 'लाल मिर्च',
    market: 'Guntur APMC',
    marketTe: 'గుంటూరు మార్కెట్',
    marketHi: 'गुंटूर मंडी',
    pricePerQuintal: 18500,
    previousPrice: 18000,
    changePercent: +2.78,
    trend: 'up',
    minPrice: 16000,
    maxPrice: 21000,
  },
  {
    crop: 'Maize',
    cropTe: 'మొక్కజొన్న',
    cropHi: 'मक्का',
    market: 'Vijayawada APMC',
    marketTe: 'విజయవాడ మార్కెట్',
    marketHi: 'विजयवाड़ा मंडी',
    pricePerQuintal: 2150,
    previousPrice: 2150,
    changePercent: 0.0,
    trend: 'stable',
    minPrice: 2000,
    maxPrice: 2250,
  },
];

export const MOCK_SOIL_REPORTS = [
  {
    labName: 'Regional Soil Testing Laboratory, Guntur',
    sampleId: 'AP-GNT-2026-8891',
    farmerName: 'Raju',
    detectedValues: {
      nitrogen: 88,
      phosphorus: 44,
      potassium: 46,
      ph: 6.6,
      organicCarbon: 0.62,
      electricalConductivity: 0.38,
      soilTexture: 'Clay Loam (నల్లరేగడి / ఒండ్రు)',
    },
    recommendationSummary: 'Optimal for Paddy, Cotton, Maize, and Pulses with standard Nitrogen balancing.',
  }
];
